### ISSUE TITLE
Use a pyside2-based approach instead of pyqt5

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [royerlab/aydin#40]
PyQt5 does not provide commercial support by default. [PySide2](https://pypi.org/project/PySide2/) is PyQt5 with a commercial-friendly lib. Migrating means only renaming imports mainly and few refinements here and there.

QDarkStyle==3.0.2 and qtpy==1.11.2 both supports pyside2 even pyside6. Switching to pyside might provide an even better business adoption.

**Comment by Abdur-rahmaanJ** [comment]
I volunteer to work on it if approved

**Comment by AhmetCanSolak** [comment]
Hello @Abdur-rahmaanJ ! Thank you for reaching out!

We are using qtpy exactly for this reason. One can install pyside2 and set `QT_API` environment variable accordingly to run Aydin with pyside2. For our distribution, we like PyQt5 better and that's why we stick to PyQt5. I hope this answers your concern. I am closing the issue but feel free to re-open the issue if you need a further discussion.

**Comment by Abdur-rahmaanJ** [comment]
@AhmetCanSolak Maybe it can be written somewhere obvious that's it's commercial friendly =^^=

**Comment by AhmetCanSolak** [comment]
We can add such sentence definitely. Feel free to find a good place in docs and a sentence and make a PR.  We can take it from there.
