### ISSUE TITLE
Using Aydin on Mac BigSur Chip M1

### ISSUE THREAD

**Issue by MeghaneSittewelle** [royerlab/aydin#43]
**Describe the bug**
I installed Aydin on my Mac, but can't open it (while worked well on a PC). I got this error on the terminal: 

```
Last login: Thu Nov 11 12:10:33 on ttys001
/Applications/aydin_0.1.9.app/Contents/MacOS/aydin ; exit;
(base) -MacBook-Pro ~ % /Applications/aydin_0.1.9.app/Contents/MacOS/aydin ; exit;
zsh: illegal hardware instruction  /Applications/aydin_0.1.9.app/Contents/MacOS/aydin
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Not sure what the problem is. I wonder if it could be a problem of compatibility with Apple M1 chip. Could you help me please?

**Desktop (please complete the following information):**
 - OS: macOS BigSur
 - Version 11.2.1 (20D74)

**Comment by AhmetCanSolak** [comment]
hello @MeghaneSittewelle ! Thank you for reaching out!

Yes this is a problem related to compatibility with Apple M series CPUs. We build our executables with Intel CPUs and with their lower level libraries currently for all operating systems. This is due to the fact that many dependencies we have are not compatible with M series chips yet. Please let me know if there is anything else I can help with!

**Comment by royerloic** [comment]
Yes, unfortunately, it is going to take some time until all the libraries we depend on eventually support M1 chips...
I am afraid you are on the bleeding edge...

**Comment by MeghaneSittewelle** [comment]
Thank you for your answers! I will continue to use it on another machine waiting for it to be compatible maybe one day, because it is a great tool !
